services:
  - type: web
    name: payment-provider-extractor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: your-secret-key-change-this-in-render-dashboard
      - key: PORT
        value: 10000
    healthCheckPath: /health
    plan: free
